import Header from "@/components/Header";
import "./globals.css";
import { Roboto } from "next/font/google";
import Providers from "@/components/Provider";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Header />
        <div className="max-w-7xl p-[20px] md:p-[50px] m-auto">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
